version: '3.8'

services:
  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: nuxt_dev
    command: npm run preview
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - "3000:3000"